core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("dashboard/", include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + i18n_patterns(
    path('i18n/', include("django.conf.urls.i18n")),
    path("", include('furnapp.urls')),
    prefix_default_language = False
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

dashboard/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('', home, name='home'),
    path('buttons/', Buttons.as_view(), name='buttons'),
    path('cards/', cards, name='cards'),
    path('colors/', colors, name='colors'),
    path('border/', border, name='border'),
    path('other/', other, name='other'),
    path('animation/', animation, name='animation'),
    path('login/', dashboard_login, name='login'),
    path('password/', forgot_password, name='password'),
    path('register/', register, name='register'),
    path('charts/', charts, name='charts'),
    path('tables/', tables, name='tables'),
    path('404/', page_404, name='page_404'),
    path('blank/', blank, name='blank'),
    path('<int:pk>-contact', contact_full, name="contact")
]

furnapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView , LogoutView
from .views import *



app_name = "furn"

urlpatterns = [
    path('', home, name="home"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path("<int:pk>/detalis/", arrivals_detail, name="arrivals_detal"),
    path("signup/", signup, name="signup"),
    path('profile/', profile, name="profile"),
    path('submit-succses/', SuccsesView.as_view(), name="succses"),
    path("start-<int:pk>-product/", star, name="star"),
    path("rate-check/", rate_check, name="rate_check"),
    # api ursl
    path('first-api/', First, name='First'),
    path('first-apiID/<int:pk>/', FirstID),
    path('ProfileAPI/', ProfileAPI, name="ProfileAPI"),
    path('ProfileID/<int:pk>/', ProfileID)
] 

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth import get_user_model
from furnapp.models import *
from django.db.models import Q
from django.utils import timezone
from django.db.models import Avg

User = get_user_model()

bugun = timezone.now().astimezone()


def home(request):
    contact_last = Contact.objects.filter(date__date=timezone.now()).count() # timezone.now()  bu yerga agar " - timezone.timedelta(1) qo`shilsa bir kun oldingi kelgan xabarlari ko`rsatadi."
    contact = Contact.objects.all().order_by('-id')[:contact_last]
    contact_count = Contact.objects.count()
    conatc_taklif = Contact.objects.filter(choices="Taklif").count() #Bu yerdagi (choices="Taklif") furnappdagi models.py Contact TAKLIF = "Taklif" 
    contact_shikoyat = Contact.objects.filter(choices="Shikoyat").count()
    users = User.objects.count()
    products = Product.objects.count()
    blog =  Blog.objects.count()
    arravial = Arrival.objects.count()
    avg_rate = Product.objects.aggregate(Avg("score"))
    context = {
        "avg_rate":avg_rate,
        "contact_count":contact_count,
        "contact_last":contact_last,
        "contact":contact,
        "contact_taklif":conatc_taklif,
        "contact_shikoyat":contact_shikoyat,
        "users":users,
        "products":products,
        "blogs":blog,
        "arravials":arravial
    }
    return render(request, 'dashboard/pages/home.html', context)

def contact_full(request, pk):
    contacts = Contact.objects.get(id=pk)
    context ={
        "contacts":contacts
    }
    return render(request, "dashboard/pages/contacts.html", context)

class Buttons(generic.TemplateView):
   template_name ="dashboard/includes/buttons.html"

def cards(request):
    return render(request, 'dashboard/includes/cards.html')

def animation(request):
    return render(request, 'dashboard/includes/animation.html')

def colors(request):
    return render(request, 'dashboard/includes/colors.html')

def border(request):
    return render(request, 'dashboard/includes/border.html')

def other(request):
    return render(request, 'dashboard/includes/other.html')

def dashboard_login(request):
    return render(request, 'dashboard/registrations/login.html')

def forgot_password(request):
    return render(request, 'dashboard/includes/forgot-password.html')

def register(request):
    return render(request, 'dashboard/registrations/register.html')

def charts(request):
    return render(request, 'dashboard/includes/charts.html')

def tables(request):
    if 'user' in request.GET:
        search = request.GET['user']
        full_search = Q(Q(first_name__icontains=search) | Q(Q(email__icontains=search)))
        profile_search = Q(Q(mobile_number__icontains=search))
        user = User.objects.filter(full_search)
        profile = Profile.objects.filter(profile_search)
    else:
        user = User.objects.all()
    context={
        "user_full":user
    }
    return render(request, 'dashboard/includes/tables.html', context)

def page_404(request):
    return render(request, 'dashboard/includes/404.html')

def blank(request):
    return render(request, 'dashboard/includes/blank.html')

templates/dashboard/includes/animation.html
{% extends 'dashboard/layouts/base.html' %}

{% block contend %}

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-1 text-gray-800">Animation Utilities</h1>
    <p class="mb-4">Bootstrap's default utility classes can be found on the official <a
            href="https://getbootstrap.com/docs">Bootstrap Documentation</a> page. The custom utilities
        below were created to extend this theme past the default utility classes built into Bootstrap's
        framework.</p>

    <!-- Content Row -->
    <div class="row">

        <!-- Grow In Utility -->
        <div class="col-lg-6">

            <div class="card position-relative">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Grow In Animation Utilty</h6>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <code>.animated--grow-in</code>
                    </div>
                    <div class="small mb-1">Navbar Dropdown Example:</div>
                    <nav class="navbar navbar-expand navbar-light bg-light mb-4">
                        <a class="navbar-brand" href="#">Navbar</a>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Dropdown
                                </a>
                                <div class="dropdown-menu dropdown-menu-right animated--grow-in"
                                    aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                        </ul>
                    </nav>
                    <p class="mb-0 small">Note: This utility animates the CSS transform property,
                        meaning it will override any existing transforms on an element being animated!
                        In this theme, the grow in animation is only being used on dropdowns within the
                        navbar.</p>
                </div>
            </div>

        </div>

        <!-- Fade In Utility -->
        <div class="col-lg-6">

            <div class="card position-relative">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Fade In Animation Utilty</h6>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <code>.animated--fade-in</code>
                    </div>
                    <div class="small mb-1">Navbar Dropdown Example:</div>
                    <nav class="navbar navbar-expand navbar-light bg-light mb-4">
                        <a class="navbar-brand" href="#">Navbar</a>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Dropdown
                                </a>
                                <div class="dropdown-menu dropdown-menu-right animated--fade-in"
                                    aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                        </ul>
                    </nav>
                    <div class="small mb-1">Dropdown Button Example:</div>
                    <div class="dropdown mb-4">
                        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown
                        </button>
                        <div class="dropdown-menu animated--fade-in" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                    <p class="mb-0 small">Note: This utility animates the CSS opacity property, meaning
                        it will override any existing opacity on an element being animated!</p>
                </div>
            </div>

        </div>

    </div>

</div>
<!-- /.container-fluid -->

{% endblock %}

templates/dashboard/includes/blank.html
{% extends 'dashboard/layouts/base.html' %}

{% block content %}Blank{% endblock %}

{% block contend %}

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

                </div>
                <!-- /.container-fluid -->

{% endblock %}

templates/dashboard/includes/border.html
{% extends 'dashboard/layouts/base.html' %}

{% block content %}Borders{% endblock %}

{% block contend %}

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-1 text-gray-800">Border Utilities</h1>
    <p class="mb-4">Bootstrap's default utility classes can be found on the official <a
            href="https://getbootstrap.com/docs">Bootstrap Documentation</a> page. The custom utilities
        below were created to extend this theme past the default utility classes built into Bootstrap's
        framework.</p>

    <!-- Content Row -->
    <div class="row">

        <!-- Border Left Utilities -->
        <div class="col-lg-6">

            <div class="card mb-4 py-3 border-left-primary">
                <div class="card-body">
                    .border-left-primary
                </div>
            </div>

            <div class="card mb-4 py-3 border-left-secondary">
                <div class="card-body">
                    .border-left-secondary
                </div>
            </div>

            <div class="card mb-4 py-3 border-left-success">
                <div class="card-body">
                    .border-left-success
                </div>
            </div>

            <div class="card mb-4 py-3 border-left-info">
                <div class="card-body">
                    .border-left-info
                </div>
            </div>

            <div class="card mb-4 py-3 border-left-warning">
                <div class="card-body">
                    .border-left-warning
                </div>
            </div>

            <div class="card mb-4 py-3 border-left-danger">
                <div class="card-body">
                    .border-left-danger
                </div>
            </div>

            <div class="card mb-4 py-3 border-left-dark">
                <div class="card-body">
                    .border-left-dark
                </div>
            </div>

        </div>

        <!-- Border Bottom Utilities -->
        <div class="col-lg-6">

            <div class="card mb-4 py-3 border-bottom-primary">
                <div class="card-body">
                    .border-bottom-primary
                </div>
            </div>

            <div class="card mb-4 py-3 border-bottom-secondary">
                <div class="card-body">
                    .border-bottom-secondary
                </div>
            </div>

            <div class="card mb-4 py-3 border-bottom-success">
                <div class="card-body">
                    .border-bottom-success
                </div>
            </div>

            <div class="card mb-4 py-3 border-bottom-info">
                <div class="card-body">
                    .border-bottom-info
                </div>
            </div>

            <div class="card mb-4 py-3 border-bottom-warning">
                <div class="card-body">
                    .border-bottom-warning
                </div>
            </div>

            <div class="card mb-4 py-3 border-bottom-danger">
                <div class="card-body">
                    .border-bottom-danger
                </div>
            </div>

            <div class="card mb-4 py-3 border-bottom-dark">
                <div class="card-body">
                    .border-bottom-dark
                </div>
            </div>

        </div>

    </div>

</div>
<!-- /.container-fluid -->

{% endblock %}

templates/dashboard/includes/charts.html
{% extends 'dashboard/layouts/base.html' %}

{% block content %}Charts{% endblock %}

{% block contend %}

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Charts</h1>
    <p class="mb-4">Chart.js is a third party plugin that is used to generate the charts in this theme.
        The charts below have been customized - for further customization options, please visit the <a target="_blank"
            href="https://www.chartjs.org/docs/latest/">official Chart.js
            documentation</a>.</p>

    <!-- Content Row -->
    <div class="row">

        <div class="col-xl-8 col-lg-7">

            <!-- Area Chart -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Area Chart</h6>
                </div>
                <div class="card-body">
                    <div class="chart-area">
                        <canvas id="myAreaChart"></canvas>
                    </div>
                    <hr>
                    Styling for the area chart can be found in the
                    <code>/js/demo/chart-area-demo.js</code> file.
                </div>
            </div>

            <!-- Bar Chart -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Bar Chart</h6>
                </div>
                <div class="card-body">
                    <div class="chart-bar">
                        <canvas id="myBarChart"></canvas>
                    </div>
                    <hr>
                    Styling for the bar chart can be found in the
                    <code>/js/demo/chart-bar-demo.js</code> file.
                </div>
            </div>

        </div>

        <!-- Donut Chart -->
        <div class="col-xl-4 col-lg-5">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Donut Chart</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-pie pt-4">
                        <canvas id="myPieChart"></canvas>
                    </div>
                    <hr>
                    Styling for the donut chart can be found in the
                    <code>/js/demo/chart-pie-demo.js</code> file.
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

{% endblock %}

templates/dashboard/includes/forgot-password.html
{% extends 'dashboard/layouts/base.html' %}

{% block content %}Forgot password{% endblock %}

{% block contend %}

<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                                    <p class="mb-4">We get it, stuff happens. Just enter your email address below
                                        and we'll send you a link to reset your password!</p>
                                </div>
                                <form class="user">
                                    <div class="form-group">
                                        <input type="email" class="form-control form-control-user"
                                            id="exampleInputEmail" aria-describedby="emailHelp"
                                            placeholder="Enter Email Address...">
                                    </div>
                                    <a href="{% url 'dashboard:login' %}" class="btn btn-primary btn-user btn-block">
                                        Reset Password
                                    </a>
                                </form>
                                <hr>
                                <div class="text-center">
                                    <a class="small" href="register.html">Create an Account!</a>
                                </div>
                                <div class="text-center">
                                    <a class="small" href="login.html">Already have an account? Login!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

templates/dashboard/includes/nav.html
{% load static %}
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form action="{% url 'dashboard:tables' %}" class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" name="user" class="form-control bg-light border-0 small"  placeholder="Search for..."
                aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                            placeholder="Search for..." aria-label="Search"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">{{ contact_last }}</span>
            </a>
            <!-- Dropdown - Alerts -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                    Contacts
                </h6>
               {% for contact in contact %}
               <a class="dropdown-item d-flex align-items-center" href="{% url 'dashboard:contact' contact.pk %}">
                <div class="mr-3">
                    <div class="icon-circle bg-primary">
                        <i class="fas fa-file-alt text-white"></i>
                    </div>
                </div>
                <div>
                    <div class="small text-gray-500">{{ contact.full_name }}</div>
                    <span class="font-weight-bold">{{ contact.choices }}</span>
                </div>
            </a>
               {% endfor %}
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
            </div>
        </li>

        <!-- Nav Item - Messages -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">7</span>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                    Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="{% static 'images/undraw_profile_1.svg' %}"
                            alt="...">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div class="font-weight-bold">
                        <div class="text-truncate">Hi there! I am wondering if you can help me with a
                            problem I've been having.</div>
                        <div class="small text-gray-500">Emily Fowler · 58m</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="{% static 'images/undraw_profile_2.svg' %}"
                            alt="...">
                        <div class="status-indicator"></div>
                    </div>
                    <div>
                        <div class="text-truncate">I have the photos that you ordered last month, how
                            would you like them sent to you?</div>
                        <div class="small text-gray-500">Jae Chun · 1d</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="{%% static 'images/undraw_profile_3.svg'}"
                            alt="...">
                        <div class="status-indicator bg-warning"></div>
                    </div>
                    <div>
                        <div class="text-truncate">Last month's report looks great, I am very happy with
                            the progress so far, keep up the good work!</div>
                        <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60"
                            alt="...">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div>
                        <div class="text-truncate">Am I a good boy? The reason I ask is because someone
                            told me that people say this to all dogs, even if they aren't good...</div>
                        <div class="small text-gray-500">Chicken the Dog · 2w</div>
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
            </div>
        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <!-- sb admin -->
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.first_name}}</span>

                <!-- not user -->
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.last_name}}</span>

                <img class="img-profile rounded-circle" src="{{ user.profile.image.url }}">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'furn:profile' %}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>

    </ul>

</nav>

templates/dashboard/includes/tables.html
{% extends 'dashboard/layouts/base.html' %}

{% block contend %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Tables</h1>
    <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
        For more information about DataTables, please visit the <a target="_blank"
            href="https://datatables.net">official DataTables documentation</a>.</p>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Email</th>
                            <th>Card Number</th>
                            <th>Address</th>
                            <th>Mobile Number</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for user in user_full %}
                        <tr>
                            <td>{{ user.first_name }}</td>
                            <td>{{ user.last_name }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.profile.card_number }}</td>
                            <td>{{ user.profile.address }}</td>
                            <td>{{ user.profile.mobile_number }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% if not user %}
                <h1>Foydalanuvchi Topilmadi</h1>
                {% endif %}
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
{% endblock %}