core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("dashboard/", include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + i18n_patterns(
    path('i18n/', include("django.conf.urls.i18n")),
    path("", include('furnapp.urls')),
    prefix_default_language = False
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

furnapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView , LogoutView
from .views import *



app_name = "furn"

urlpatterns = [
    path('', home, name="home"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path("<int:pk>/detalis/", arrivals_detail, name="arrivals_detal"),
    path("signup/", signup, name="signup"),
    path('profile/', profile, name="profile"),
    path('submit-succses/', SuccsesView.as_view(), name="succses"),
    path("start-<int:pk>-product/", star, name="star"),
    path("rate-check/", rate_check, name="rate_check"),
    # api ursl
    path('first-api/', First, name='First'),
    path('first-apiID/<int:pk>/', FirstID),
    path('ProfileAPI/', ProfileAPI, name="ProfileAPI"),
    path('ProfileID/<int:pk>/', ProfileID)
] 

furnapp/models.py
from audioop import add
from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image
from django.utils.timezone import datetime
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse

class MyUser(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    is_organiser = models.BooleanField(default=False)
    is_agent = models.BooleanField(default=False)

class Profile(models.Model):
    class Meta:
        verbose_name = "My Profile"
        verbose_name_plural = "Profile"
    custom_user = models.OneToOneField(MyUser, on_delete=models.CASCADE)
    image = models.ImageField(default="arrivals5.png", upload_to="profile")
    bio = models.CharField(max_length=100, default="bio", null=True, blank=True)
    card_number = models.IntegerField(default=2500, null=True,blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    mobile_number = models.IntegerField(default=998931742328, null=True, blank=True)
    


    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

class Carousel(models.Model):

    img = models.ImageField()
    slider_title = models.CharField(max_length=100)
    title = models.CharField(max_length=200)
    aboute = models.TextField(max_length=700)
    price = models.IntegerField(default=1)
    old_price = models.IntegerField(default=2)

    def __str__(self):
        return self.title

class Arrival(models.Model):
    arrivals_img = models.ImageField()
    arrivals_title = models.CharField(max_length=200)
    arrivals_price = models.IntegerField(default=10)
    category = models.ForeignKey("Category",blank=True, on_delete=models.CASCADE)

    #asosiy ma`lumotlar uchun
    arrivals_size  = models.CharField(max_length=30)
    arrivals_text = models.TextField(max_length=700)
    
    def __str__(self):
        return self.arrivals_title



class Product(models.Model):
    title = models.CharField(max_length=200)
    price = models.IntegerField(default=1, null=True, blank=True)
    img = models.ImageField(upload_to="images/")
    score = models.IntegerField(default=0,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(0),
        ]
    )

    def __str__(self):
        return str(f"id:{self.pk} score:{self.score} title:{self.title}")

class Comment(models.Model):
    post = models.ForeignKey(Product,on_delete=models.CASCADE,related_name='comments')
    authour = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    message = models.CharField(max_length=50)
    rate_product = models.IntegerField(default=0)
    active = models.BooleanField(default=True)

    def __str__(self):
        return str(f"post author - {self.authour}")

class Blog(models.Model):
    img = models.ImageField()
    title = models.CharField(max_length=200)
    date = models.DateField(default=datetime.now)
    aboute = models.TextField(max_length=700)

    def __str__(self):
        return self.title



 
class Category(models.Model):
    class Meta:
        verbose_name = 'My Category'
        verbose_name_plural = 'My Categorys bob'
        
    category_name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.category_name

class Contact(models.Model):
    TAKLIF = "Taklif"
    SHIKOYAT = "Shikoyat"
    CONTACT_CHOICES = [
        (TAKLIF, "Taklif"),
        (SHIKOYAT, "Shikoyat")
    ]
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    choices = models.CharField(max_length=8, choices=CONTACT_CHOICES, default=TAKLIF)
    mobile = models.IntegerField(default=9989)
    message = models.TextField(max_length=700)
    date = models.DateTimeField(auto_now=add)
    def __str__(self):
        return self.choices

templates/pages/home.html
{% extends 'layouts/base.html' %}

{% block title %}Home Page{% endblock title %}

{% block content %}
    {% include 'includes/carousel.html' %}
    {% include 'includes/discover.html' %}
    {% include 'includes/new-arrivals.html' %}
    {% include 'includes/sofa-collection.html' %}
    {% include 'includes/feature.html' %}
    {% include 'includes/contact.html' %}
    {% include 'includes/blog.html' %}
    {% include 'includes/clients.html' %}
{% endblock content %}

templates/pages/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile Page</title>
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>

    <div>
        <img src="{{ user.profile.image.url }}" alt="">
        <h3>{{ user.first_name }}</h3>
        <h3>{{ user.email }}</h3>
        <h3>{{ user.profile.bio }}</h3>
        <span>{{ user.profile.card_number }}</span>
        <form  method="post" enctype="multipart/form-data">
            {% load widget_tweaks %}
            {% csrf_token %}
          <div class="row">
            <div class="col-md-6 form-group mt-5">
                {% render_field user_form.first_name type="text" class="form-control" %}
            </div>
            <div class="col-md-6 form-group mt-5">
                {% render_field user_form.last_name type="text" class="form-control" %}
            </div>
            <div class="col-md-6 form-group mt-5">
                {% render_field user_form.email type="text" class="form-control" %}
            </div>
            <div class="col-md-6 form-group mt-5">
                {% render_field profile_form.bio type="text" class="form-control" %}
            </div>
            <div class="col-md-6 form-group mt-5">
                {% render_field profile_form.card_number type="text" class="form-control" %}
            </div>
            <div class="col-md-6 form-group mt-5">
                {% render_field profile_form.address type="text" class="form-control" %}
            </div>
            <div class="col-md-6 form-group mt-5">
                {% render_field profile_form.mobile_number type="text" class="form-control" %}
            </div>
            <div class="col-md-6 form-group mt-5">
                {% render_field profile_form.card_number type="text" class="form-control" %}
            </div>
            <div class="col-md-6 form-group mt-5">
                {% render_field profile_form.image type="file" class="form-control" %}
            </div>
          </div>
            <button type="submit">Update</button>
        </form>
    </div>

   

</body>

</html>

templates/pages/star.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="UTF-8">
</head>
<title>Star rating Product</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
    integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


<body>

    <style>
        * {
            margin: 0;
            padding: 0;
        }

        /* .box{
            position: relative;
        } */
        body {
            display: grid;
            place-items: center;
            min-height: 100vh;
        }

        .checked {
            color: gold;
        }

        .btns {
            background-color: inherit !important;
            border: 0 !important;
            font-size: 30px;
        }

        a {
            position: absolute;
            top: 100px;
            left: 100px;
            text-decoration: none;
            font-size: 50px;
            color: black;
            text-transform: uppercase;
            font-family: serif;
            transition: 1s all;

        }
        .comment{
            overflow: scroll !important;
            width: 400px;
            height: 400px;
            position: absolute;
            top: 300px;
            right: 200px;
        }
        #id_authour{
            display: none;
        }
    </style>
    <div class="comment">
        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
            <h3 class="font-weight-bold">
                {{ comment.authour.first_name }}: {{ comment.message }} {{ comment.rate_product }}
            </h3>
        </div>
        {% endfor %}
        {% if not comments %}
        <h1>No comments yet</h1>
        {% endif %}
    </div>
    <div class="box">
        <a class="fa-solid fa-arrow-left" href="/#product"></a>
        <div>
            <img src="{{ which_one.img.url }}" height="500">
            <h1>{{ which_one.title }}</h1>
        </div>
        <form class="rate-form" method="post" id="{{ which_one.id }}">
            {% csrf_token %}
            <button type="submit" class="fa-solid fa-star btns" id="first"></button>
            <button type="submit" class="fa-solid fa-star btns" id="second"></button>
            <button type="submit" class="fa-solid fa-star btns" id="third"></button>
            <button type="submit" class="fa-solid fa-star btns" id="fourth"></button>
            <button type="submit" class="fa-solid fa-star btns" id="fifth"></button>
        </form>
        {% if  request.user.is_authenticated %}
        <form method="post" class="d-flex mt-4">
            {% csrf_token %}
            {% load widget_tweaks %}
            {{ comment_form.authour }}
            {{ comment_form.rate_product }}
            {% render_field comment_form.message type="text" class="form-control" placeholder="Leave comment" %}
            <button type="submit" class="btn btn-info">Send</button>
        </form>
        {% endif %}
        <div id="confirm-box"></div>
        
    </div>

    <script src="{% static 'js/rate.js' %}"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="{% static 'js/home.js' %}"></script>
    <script>
        let autor = document.querySelector('#id_authour')
        let options = autor.querySelectorAll('option')

        options.forEach(function (item) {
            if (item.innerHTML == '{{ request.user.email }}') {
                item.selected = true
            }
            else {
                item.remove()
            }
        })

        
    </script>
</body>

</html>

templates/pages/succses.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Succses</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
    <style>
        body {
            background-color: #000000;
            background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100%25' height='100%25' viewBox='0 0 1600 800'%3E%3Cg %3E%3Cpolygon fill='%23220000' points='1600 160 0 460 0 350 1600 50'/%3E%3Cpolygon fill='%23440000' points='1600 260 0 560 0 450 1600 150'/%3E%3Cpolygon fill='%23660000' points='1600 360 0 660 0 550 1600 250'/%3E%3Cpolygon fill='%23880000' points='1600 460 0 760 0 650 1600 350'/%3E%3Cpolygon fill='%23A00' points='1600 800 0 800 0 750 1600 450'/%3E%3C/g%3E%3C/svg%3E");
            background-attachment: fixed;
            background-size: cover;
            display: grid;
            place-items: center;
            min-height: 100vh;
        }

        a {
            position: absolute;
            top: 70px;
            left: 240px;
            text-decoration: none;
            color: #fff;
            font-size: 2rem;
            padding: 5px 10px;
            border-radius: 5px;
            transition: 0.5s all;
        }

        a:hover {
            box-shadow: inset 0px -100px #fff;
            color: #330033;
        }
    </style>

    <div style="position: relative;">
        <h1 class="text-center text-light">Your request <span class="text-danger">successfully</span> submit</h1>
        <a href="{% url 'furn:home' %}">Go Home</a>
    </div>
</body>

</html>

templates/pages/translate.html
{% load i18n %}

<form action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}">
    <select name="language" onchange="this.form.submit()">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
        <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected{% endif %}>
            {{ language.name_local }} ({{ language.code }})
        </option>
        {% endfor %}
    </select>

</form>
<button type="button" class="button"><a href="/home/">Home</a></button>
<h1>{% trans "mening ishim" %}</h1>
<h3>{% trans "bahor" %}</h3>
<h1>{% trans "salom hammaga mening ismim Durbek" %}</h1>
<style>