core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("dashboard/", include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + i18n_patterns(
    path('i18n/', include("django.conf.urls.i18n")),
    path("", include('furnapp.urls')),
    prefix_default_language = False
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

dashboard/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('', home, name='home'),
    path('buttons/', Buttons.as_view(), name='buttons'),
    path('cards/', cards, name='cards'),
    path('colors/', colors, name='colors'),
    path('border/', border, name='border'),
    path('other/', other, name='other'),
    path('animation/', animation, name='animation'),
    path('login/', dashboard_login, name='login'),
    path('password/', forgot_password, name='password'),
    path('register/', register, name='register'),
    path('charts/', charts, name='charts'),
    path('tables/', tables, name='tables'),
    path('404/', page_404, name='page_404'),
    path('blank/', blank, name='blank'),
    path('<int:pk>-contact', contact_full, name="contact")
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth import get_user_model
from furnapp.models import *
from django.db.models import Q
from django.utils import timezone
from django.db.models import Avg

User = get_user_model()

bugun = timezone.now().astimezone()


def home(request):
    contact_last = Contact.objects.filter(date__date=timezone.now()).count() # timezone.now()  bu yerga agar " - timezone.timedelta(1) qo`shilsa bir kun oldingi kelgan xabarlari ko`rsatadi."
    contact = Contact.objects.all().order_by('-id')[:contact_last]
    contact_count = Contact.objects.count()
    conatc_taklif = Contact.objects.filter(choices="Taklif").count() #Bu yerdagi (choices="Taklif") furnappdagi models.py Contact TAKLIF = "Taklif" 
    contact_shikoyat = Contact.objects.filter(choices="Shikoyat").count()
    users = User.objects.count()
    products = Product.objects.count()
    blog =  Blog.objects.count()
    arravial = Arrival.objects.count()
    avg_rate = Product.objects.aggregate(Avg("score"))
    context = {
        "avg_rate":avg_rate,
        "contact_count":contact_count,
        "contact_last":contact_last,
        "contact":contact,
        "contact_taklif":conatc_taklif,
        "contact_shikoyat":contact_shikoyat,
        "users":users,
        "products":products,
        "blogs":blog,
        "arravials":arravial
    }
    return render(request, 'dashboard/pages/home.html', context)

def contact_full(request, pk):
    contacts = Contact.objects.get(id=pk)
    context ={
        "contacts":contacts
    }
    return render(request, "dashboard/pages/contacts.html", context)

class Buttons(generic.TemplateView):
   template_name ="dashboard/includes/buttons.html"

def cards(request):
    return render(request, 'dashboard/includes/cards.html')

def animation(request):
    return render(request, 'dashboard/includes/animation.html')

def colors(request):
    return render(request, 'dashboard/includes/colors.html')

def border(request):
    return render(request, 'dashboard/includes/border.html')

def other(request):
    return render(request, 'dashboard/includes/other.html')

def dashboard_login(request):
    return render(request, 'dashboard/registrations/login.html')

def forgot_password(request):
    return render(request, 'dashboard/includes/forgot-password.html')

def register(request):
    return render(request, 'dashboard/registrations/register.html')

def charts(request):
    return render(request, 'dashboard/includes/charts.html')

def tables(request):
    if 'user' in request.GET:
        search = request.GET['user']
        full_search = Q(Q(first_name__icontains=search) | Q(Q(email__icontains=search)))
        profile_search = Q(Q(mobile_number__icontains=search))
        user = User.objects.filter(full_search)
        profile = Profile.objects.filter(profile_search)
    else:
        user = User.objects.all()
    context={
        "user_full":user
    }
    return render(request, 'dashboard/includes/tables.html', context)

def page_404(request):
    return render(request, 'dashboard/includes/404.html')

def blank(request):
    return render(request, 'dashboard/includes/blank.html')

templates/dashboard/pages/contacts.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{{ contacts.choices }}</title>
</head>

<body>
    <style>
        body {
            display: grid;
            background-color: #000000;
            background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100%25' height='100%25' viewBox='0 0 1600 800'%3E%3Cg fill-opacity='0.98'%3E%3Cpolygon fill='%23220000' points='1600 160 0 460 0 350 1600 50'/%3E%3Cpolygon fill='%23440000' points='1600 260 0 560 0 450 1600 150'/%3E%3Cpolygon fill='%23660000' points='1600 360 0 660 0 550 1600 250'/%3E%3Cpolygon fill='%23880000' points='1600 460 0 760 0 650 1600 350'/%3E%3Cpolygon fill='%23A00' points='1600 800 0 800 0 750 1600 450'/%3E%3C/g%3E%3C/svg%3E");
            background-attachment: fixed;
            background-size: cover;
            place-items: center;
            min-height: 100vh;
        }

        .gohome {
            position: absolute;
            top: 30px;
            text-decoration: none;
            color: #fff;
            left: 40px;
            font-size: 2rem;
            z-index: 10;
        }

        .mobile{
            margin-right: 40px;
            margin-left: 30px;
        }
        .email{
            margin-left: 10px;
        }
    </style>



    <a class="gohome" href="{% url 'dashboard:home' %}"><i class="fa-solid fa-arrow-left"></i></a>
    <div class="context">
        <div class="container text-light" >
            <h1 class="full_name">To`liq Ismi: {{ contacts.full_name }}</h1>
            <span class="mt-4 mb-4">Turi: {{ contacts.choices }}</span>
            <p class="msg">Xabar: {{ contacts.message}}</p>
            <div class="d-flex justify-content-between">
                <div style="text-align: center;">
                    <a href="tel:{{ contacts.mobile }}" class="mobile "><i class="fa-solid fa-phone fa-lg text-light"></i></a>
                    <p>Telefon</p>
                </div>
                <div>
                    <a href="mailto:{{ contacts.email }}" class="email"><i class="fa-solid fa-paper-plane fa-lg text-light"></i></a>
                    <p>Email</p>
                </div>
                <div>
                    
                    <div class="d-flex">
                        <span>
                            <div class="d.flex">
                            <!-- <i class="fa-regular fa-calendar-check fa-lg text-light"></i> -->
                            <p>{{ contacts.date }}</p>
                            </div>
                            <p>Yubirlgan Vaqt</p>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>




</body>

</html>

templates/dashboard/pages/home.html
{% extends 'dashboard/layouts/base.html' %}
{% block content %}Home{% endblock content %}

{% block contend %}
    {% include 'dashboard/includes/index.html' %}
{% endblock %}