core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("dashboard/", include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + i18n_patterns(
    path('i18n/', include("django.conf.urls.i18n")),
    path("", include('furnapp.urls')),
    prefix_default_language = False
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

furnapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView , LogoutView
from .views import *



app_name = "furn"

urlpatterns = [
    path('', home, name="home"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path("<int:pk>/detalis/", arrivals_detail, name="arrivals_detal"),
    path("signup/", signup, name="signup"),
    path('profile/', profile, name="profile"),
    path('submit-succses/', SuccsesView.as_view(), name="succses"),
    path("start-<int:pk>-product/", star, name="star"),
    path("rate-check/", rate_check, name="rate_check"),
    # api ursl
    path('first-api/', First, name='First'),
    path('first-apiID/<int:pk>/', FirstID),
    path('ProfileAPI/', ProfileAPI, name="ProfileAPI"),
    path('ProfileID/<int:pk>/', ProfileID)
] 

templates/includes/blog.html
{% load static %}
<section id="blog" class="blog">
    <div class="container">
        <div class="section-header">
            <h2>latest blog</h2>
        </div>
        <!--/.section-header-->
        <div class="blog-content">
            <div class="row">
                {% for y in blog %}
                <div class="col-sm-4">
                    <div class="single-blog">
                        <div class="single-blog-img">
                            <img src="{{ y.img.url }}" alt="blog image" style="width: 400px;">
                            <div class="single-blog-img-overlay"></div>
                        </div>
                        <div class="single-blog-txt">
                            <h2><a href="#">{{ y.title }}</a></h2>
                            <h3>Date: {{ y.date }}</h3>
                            <p>
                                {{ y.aboute }}
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!--/.container-->

</section>

templates/includes/carousel.html
{% load i18n %}
{% load static %}

<div id="header-carousel" class="carousel slide carousel-fade" data-ride="carousel">
    <!--/.carousel-indicator -->
    <ol class="carousel-indicators">
        <li data-target="#header-carousel" data-slide-to="0" class="active"><span class="small-circle"></span>
        </li>
        <li data-target="#header-carousel" data-slide-to="1"><span class="small-circle"></span></li>
        <li data-target="#header-carousel" data-slide-to="2"><span class="small-circle"></span></li>
        <li data-target="#header-carousel" data-slide-to="3"><span class="small-circle"></span></li>
    </ol><!-- /ol-->
    <!--/.carousel-indicator -->

    <!--/.carousel-inner -->
    <div class="carousel-inner" role="listbox">
        <!-- .item -->
        <div class="item active">
            <div class="single-slide-item slide1">
                <div class="container">
                    <div class="welcome-hero-content">
                        <div class="row">
                            <div class="col-sm-7">
                                <div class="single-welcome-hero">
                                    <div class="welcome-hero-txt">
                                        <h4>{% trans "Ajoyib dizayn kolleksiyasi" %}</h4>
                                        <h2>{% trans "Valvet Accent kreslo" %} </h2>
                                        <p>Lorem Ipsum Dolor Sit Amet, Consectetur Adipisicing Elit, Sed Do Eiuiana
                                            Smod Tempor Ut Labore Et Dolore Magna Aliqua. Ut Enim Ad Minim Veniam, Quis
                                            Nostrud Exercitation Ullamco Laboris Nisi Ut Aliquip.
                                        </p>
                                        <div class="packages-price">
                                            <p>
                                                $ 465
                                                <del>$ 565</del>
                                            </p>
                                        </div>
                                        <button class="btn-cart welcome-add-cart" onclick="window.location.href='#'">
                                            <span class="lnr lnr-plus-circle"></span>
                                            {% trans "Karta qo`shish" %}
                                        </button>
                                        <button class="btn-cart welcome-add-cart welcome-more-info"
                                            onclick="window.location.href='#'">
                                            {% trans "qo'shimcha ma'lumot" %}
                                        </button>
                                    </div>
                                    <!--/.welcome-hero-txt-->
                                </div>
                                <!--/.single-welcome-hero-->
                            </div>
                            <!--/.col-->
                            <div class="col-sm-5">
                                <div class="single-welcome-hero">
                                    <div class="welcome-hero-img">
                                        <img src="{% static 'images/slider/slider1.png' %}" alt="slider image"
                                            width="500">
                                    </div>
                                    <!--/.welcome-hero-txt-->
                                </div>
                                <!--/.single-welcome-hero-->
                            </div>
                            <!--/.col-->
                        </div>
                        <!--/.row-->
                    </div>
                    <!--/.welcome-hero-content-->
                </div><!-- /.container-->
            </div><!-- /.single-slide-item-->

        </div><!-- /.item .active-->
        {% for y in base %}
        <div class="item">
            <div class="single-slide-item slide1">
                <div class="container">
                    <div class="welcome-hero-content">
                        <div class="row">
                            <div class="col-sm-7">
                                <div class="single-welcome-hero">
                                    <div class="welcome-hero-txt">
                                        <h4>{% trans "ajoyib dizayn kolleksiyasi" %}</h4>
                                        <h2>{{ y.title }}</h2>
                                        <p>
                                            {{ y.aboute }}
                                        </p>
                                        <div class="packages-price">
                                            <p>
                                                $ {{ y.price }}
                                                <del>$ {{ y.old_price }}</del>
                                            </p>
                                        </div>
                                        <button class="btn-cart welcome-add-cart" onclick="window.location.href='#'">
                                            <span class="lnr lnr-plus-circle"></span>
                                            {% trans "Karta qo`shish" %}
                                        </button>
                                        <button class="btn-cart welcome-add-cart welcome-more-info"
                                            onclick="window.location.href='#'">
                                            {% trans "qo'shimcha ma'lumot" %}
                                        </button>
                                    </div>
                                    <!--/.welcome-hero-txt-->
                                </div>
                                <!--/.single-welcome-hero-->
                            </div>
                            <!--/.col-->
                            <div class="col-sm-5">
                                <div class="single-welcome-hero">
                                    <div class="welcome-hero-img">
                                        <img src="{{ y.img.url }}" alt="slider image" width="500">
                                    </div>
                                    <!--/.welcome-hero-txt-->
                                </div>
                                <!--/.single-welcome-hero-->
                            </div>
                            <!--/.col-->
                        </div>
                        <!--/.row-->
                    </div>
                    <!--/.welcome-hero-content-->
                </div><!-- /.container-->
            </div><!-- /.single-slide-item-->

        </div><!-- /.item .active-->
        {% endfor %}

    </div><!-- /.carousel-inner-->

</div>

templates/includes/feature.html
{% load i18n %}
{% load static %}

<style>
    .gray{
        color: gray !important;
    }
</style>

<section id="product" class="feature">
    <div class="container">
        <div class="section-header">
            <h2>{% trans "ko`rsatilgan mahsulotlar" %}</h2>
        </div>
        <!--/.section-header-->
        <div class="feature-content">
            <div class="row">
                {% for y in products %}
                <div class="col-sm-3 all">
                    <div class="single-feature">
                        <img src="{{ y.img.url }}" alt="feature image" width="300">
                        <div class="single-feature-txt text-center">
                            <a href="{% url 'furn:star' y.id %}">
                                <p>
                                    <i class="fa fa-star gray star" id="first"></i>
                                    <i class="fa fa-star gray star" id="second"></i>
                                    <i class="fa fa-star gray star" id="third"></i>
                                    <i class="fa fa-star gray star" id="fourth"></i>
                                    <i class="fa fa-star gray star" id="fifth"></i>
                                    <span class="feature-review">{{ y.score }}</span>
                                </p>
                            </a>
                            <h3>{% trans "Mahsulot" %}</h3>
                            <h5>${{ y.price }}</h5>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% if not products %}
                <div class="col-sm-3 ">
                    <div class="single-feature">
                        <img src="{% static 'images/features/none.png' %}" alt="feature image" width="300">
                        <div class="single-feature-txt text-center">
                            <p>
                                <span class="spacial-feature-icon"><i class="fa fa-star"></i></span>
                                <span class="spacial-feature-icon"><i class="fa fa-star"></i></span>
                                <span class="spacial-feature-icon"><i class="fa fa-star"></i></span>
                                <span class="spacial-feature-icon"><i class="fa fa-star"></i></span>
                                <span class="spacial-feature-icon"><i class="fa fa-star"></i></span>
                                <span class="feature-review">(0 review)</span>
                            </p>
                            <h3><a href="#">{% trans "Product not found!" %}</a></h3>
                            <h5>$0</h5>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    <!--/.container-->
</section>

templates/includes/footer.html
<!--newsletter strat -->
{% load i18n %}
{% load static %}
<section id="newsletter" class="newsletter">
    <div class="container">
        <div class="hm-footer-details">
            <div class="row">
                <div class=" col-md-3 col-sm-6 col-xs-12">
                    <div class="hm-footer-widget">
                        <div class="hm-foot-title">
                            <h4>{% trans "ma `lumot" %}</h4>
                        </div>
                        <!--/.hm-foot-title-->
                        <div class="hm-foot-menu">
                            <ul>
                                <li><a href="#">{% trans "Biz haqimizda" %}</a></li>
                                <!--/li-->
                                <li class="scroll"><a href="#contactus">contact us</a></li>
                                <!--/li-->
                                <li><a href="#">{% trans "Yangiliklar" %}</a></li>
                                <!--/li-->
                                <li><a href="#">{% trans "do'kon" %}</a></li>
                                <!--/li-->
                            </ul>
                            <!--/ul-->
                        </div>
                        <!--/.hm-foot-menu-->
                    </div>
                    <!--/.hm-footer-widget-->
                </div>
                <!--/.col-->
                <div class=" col-md-3 col-sm-6 col-xs-12">
                    <div class="hm-footer-widget">
                        <div class="hm-foot-title">
                            <h4>{% trans "to'plamlar" %}</h4>
                        </div>
                        <!--/.hm-foot-title-->
                        <div class="hm-foot-menu">
                            <ul>
                                <li><a href="#">{% trans "yog`ochli stul" %}</a></li>
                                <!--/li-->
                                <li><a href="#">{% trans "qirollik mato divan" %}</a></li>
                                <!--/li-->
                                <li><a href="#">{% trans "aksent kreslo" %}</a></li>
                                <!--/li-->
                                <li><a href="#">{% trans "yotoq" %}</a></li>
                                <!--/li-->
                                <li><a href="#">{% trans "osilgan lampa" %}</a></li>
                                <!--/li-->
                            </ul>
                            <!--/ul-->
                        </div>
                        <!--/.hm-foot-menu-->
                    </div>
                    <!--/.hm-footer-widget-->
                </div>
                <!--/.col-->
                <div class=" col-md-3 col-sm-6 col-xs-12">
                    <div class="hm-footer-widget">
                        <div class="hm-foot-title">
                            <h4>{% trans "mening hisoblarim" %}</h4>
                        </div>
                        <!--/.hm-foot-title-->
                        <div class="hm-foot-menu">
                            <ul>
                                <li><a href="{% url 'furn:profile' %}">{% trans "mening hisobim" %}</a></li>
                                <!--/li-->
                                <li><a href="#">{% trans "istaklar ro`yxati" %}</a></li>
                                <!--/li-->
                                <li><a href="#">{% trans "Jamiyat" %}</a></li>
                                <!--/li-->
                                <li><a href="#">{% trans "buyurtma tarixi" %}</a></li>
                                <!--/li-->
                                <li><a href="#">{% trans "mening avaram" %}</a></li>
                                <!--/li-->
                            </ul>
                            <!--/ul-->
                        </div>
                        <!--/.hm-foot-menu-->
                    </div>
                    <!--/.hm-footer-widget-->
                </div>
                <!--/.col-->
                <div class=" col-md-3 col-sm-6  col-xs-12">
                    <div class="hm-footer-widget">
                        <div class="hm-foot-title">
                            <h4>{% trans "yangiliklar xati" %}</h4>
                        </div>
                        <!--/.hm-foot-title-->
                        <div class="hm-foot-para">
                            <p>
                                {% trans "Eng so'nggi yangiliklar, yangilanishlar va ma'lumotlarni olish uchun obuna bo'ling!" %}
                            </p>
                        </div>
                        <!--/.hm-foot-para-->
                        <div class="hm-foot-email">
                            <div class="foot-email-box">
                               
                            </div>
                        </div>
                        <!--/.hm-foot-email-->
                    </div>
                    <!--/.hm-footer-widget-->
                </div>
                <!--/.col-->
            </div>
            <!--/.row-->
        </div>
        <!--/.hm-footer-details-->

    </div>
    <!--/.container-->

</section>
<!--/newsletter-->
<!--newsletter end -->
<!--footer start-->
<footer id="footer" class="footer">
    <div class="container">
        <div class="hm-footer-copyright text-center">
            <div class="footer-social">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-instagram"></i></a>
                <a href="#"><i class="fa fa-linkedin"></i></a>
                <a href="#"><i class="fa fa-pinterest"></i></a>
                <a href="#"><i class="fa fa-behance"></i></a>
            </div>
            <p>
                &copy;{% trans "Mualliflik huquqi" %} <a href="https://github.com/durbek11">Durbek</a>  {% trans "tomonidan ishlab chiqarilgan" %}
            </p>
            <!--/p-->
        </div>
        <!--/.text-center-->
    </div>
    <!--/.container-->

    <div id="scroll-Top">
        <div class="return-to-top">
            <i class="fa fa-angle-up " id="scroll-top" data-toggle="tooltip" data-placement="top" title=""
                data-original-title="Back to Top" aria-hidden="true"></i>
        </div>

    </div>
    <!--/.scroll-Top-->

</footer>
<!--/.footer-->
<!--footer end-->

templates/includes/navigation.html
{% load i18n %}
{% load static %}

<!--welcome-hero start -->
<header id="home" class="welcome-hero">
    <div class="top-area">
        <div class="header-area">
            <!-- Start Navigation -->
            <nav class="navbar navbar-default bootsnav  navbar-sticky navbar-scrollspy" data-minus-value-desktop="70"
                data-minus-value-mobile="55" data-speed="1000">

                <!-- Start Top Search -->
                <div class="top-search">
                    <div class="container">
                        <form method="get" action="#product">
                            <div class="input-group " style="display: flex;">
                                <input type="text" name="product" class="form-control" placeholder="Search">
                                <button class="input-group-addon" type="submit"><i class="fa fa-search"></i></button>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- End Top Search -->

                <div class="container">
                    <!-- Start Atribute Navigation -->
                    <div class="attr-nav">
                        <ul>
                            <li class="search">
                                <a href="#"><span class="lnr lnr-magnifier"></span></a>
                            </li>
                            <!--/.search-->
                            <li class="nav-setting">
                                <a href="#"><span class="lnr lnr-cog"></span></a>
                            </li>
                            {% if request.user.is_authenticated %}
                            <li class="nav-setting">
                                <a href="{% url 'furn:profile' %}"><span class="lnr lnr-user"></span></a>
                            </li>
                            {% endif %}
                            <!--/.search-->
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <span class="lnr lnr-cart"></span>
                                    <span class="badge badge-bg-1">2</span>
                                </a>
                                <ul class="dropdown-menu cart-list s-cate">
                                    <li class="single-cart-list">
                                        <a href="#" class="photo"><img
                                                src="{% static 'images/collection/arrivals1.png' %} " class="cart-thumb"
                                                alt="image" /></a>
                                        <div class="cart-list-txt">
                                            <h6><a href="#">{% trans "qo`l" %} <br>{% trans "stul" %}</a></h6>
                                            <p>1 x - <span class="price">$180.00</span></p>
                                        </div>
                                        <!--/.cart-list-txt-->
                                        <div class="cart-close">
                                            <span class="lnr lnr-cross"></span>
                                        </div>
                                        <!--/.cart-close-->
                                    </li>
                                    <!--/.single-cart-list -->
                                    <li class="single-cart-list">
                                        <a href="#" class="photo"><img
                                                src="{% static 'images/collection/arrivals2.png' %}" class="cart-thumb"
                                                alt="image" /></a>
                                        <div class="cart-list-txt">
                                            <h6><a href="#">{% trans "yagona" %}<br>{% trans "kreslo" %}</a></h6>
                                            <p>1 x - <span class="price">$180.00</span></p>
                                        </div>
                                        <!--/.cart-list-txt-->
                                        <div class="cart-close">
                                            <span class="lnr lnr-cross"></span>
                                        </div>
                                        <!--/.cart-close-->
                                    </li>
                                    <!--/.single-cart-list -->
                                    <li class="single-cart-list">
                                        <a href="#" class="photo"><img
                                                src="{% static 'images/collection/arrivals3.png' %}" class="cart-thumb"
                                                alt="image" /></a>
                                        <div class="cart-list-txt">
                                            <h6><a href="#">{% trans "yog'och" %} <br>{% trans "kreslo" %} </a></h6>
                                            <p>1 x - <span class="price">$180.00</span></p>
                                        </div>
                                        <!--/.cart-list-txt-->
                                        <div class="cart-close">
                                            <span class="lnr lnr-cross"></span>
                                        </div>
                                        <!--/.cart-close-->
                                    </li>
                                    <!--/.single-cart-list -->
                                    <li class="total">
                                        <span>{% trans "jami" %}: $0.00</span>
                                        <button class="btn-cart pull-right" onclick="window.location.href='#'">{% trans "
                                            savatni ko'rish" %}
                                        </button>
                                    </li>
                                </ul>
                            </li>
                            <!--/.dropdown-->
                        </ul>
                    </div>
                    <!--/.attr-nav-->
                    <!-- End Atribute Navigation -->

                    <!-- Start Header Navigation -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
                            <i class="fa fa-bars"></i>
                        </button>
                        <a class="navbar-brand" href="#">sine<span>mkt</span>.</a>

                    </div>
                    <!--/.navbar-header-->
                    <!-- End Header Navigation -->

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse menu-ui-design" id="navbar-menu" style="background-color: #fff;">
                        <ul class="nav navbar-nav navbar-center" data-in="fadeInDown" data-out="fadeOutUp">
                            <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                                <input name="next" type="hidden" value="{{ redirect_to }}">
                                <select name="language" onchange="this.form.submit()">
                                    {% get_current_language as LANGUAGE_CODE %}
                                    {% get_available_languages as LANGUAGES %}
                                    {% get_language_info_list for LANGUAGES as languages %}
                                    {% for language in languages %}
                                    <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                        {{ language.name_local }} ({{ language.code }})
                                    </option>
                                    {% endfor %}
                                </select>
                            
                            </form>
                            <li class=" scroll active"><a href="#home">{% trans "uy" %}</a></li>
                            <li class="scroll"><a href="#new-arrivals">{% trans "yangi kelgan" %}</a></li>
                            <li class="scroll"><a href="#product">{% trans "Mahsulotlar" %}</a></li>
                            <li class="scroll"><a href="#blog">{% trans "blok" %}</a></li>
                            <li class="scroll"><a href="#contactus">{% trans "Aloqa" %}</a></li>
                            {% if not request.user.is_authenticated %}
                            <li><a href="{% url 'furn:signup' %}">{% trans "ro`yhatdan o`tish" %}</a></li>
                            <li><a href="{% url 'furn:login' %}">{% trans "Kirish" %}</a></li>
                            {% endif %}
                            {% if request.user.is_authenticated %}
                            <li><a href="{% url 'furn:logout' %}">{% trans "Chiqish" %}</a></li>
                            {% endif %}
                            {% if request.user.is_organiser %}
                            <li><a href="/dashboard/">{% trans "Asboblar paneli" %}</a></li>
                            {% endif %}
                        </ul>
                        <!--/.nav -->
                    </div><!-- /.navbar-collapse -->
                </div>
                <!--/.container-->
            </nav>
            <!--/nav-->
            <!-- End Navigation -->
        </div>
        <!--/.header-area-->
        <div class="clearfix"></div>

    </div>

</header>
<!--/.welcome-hero-->
<!--welcome-hero end -->

templates/includes/new-arrivals.html
{% load i18n %}
{% load static %}

<style>
    .links{
        border: 1px solid aqua !important;
        text-decoration: none !important;
        display: inline-block !important;
        padding: 10px 15px !important;
        margin-top: 10px;
        margin-left: 20px;
    }
</style>

<section id="new-arrivals" class="new-arrivals">
    <div class="container">
        <div class="section-header">
            <h2>{% trans "yangi kelganlar" %}</h2>
            <a class="links" href="{% url 'furn:home' %}#new-arrivals">{% trans "hammasi" %}</a>
            {% for category in categoryes %}
            <a class="links" href="{% url 'furn:home' %}?category={{ category.category_name }}#new-arrivals">{{ category.category_name }}</a>
            {% endfor %}
        </div>
        <!--/.section-header-->
        <div class="new-arrivals-content">
            <div class="row">
                {% for y in arrivals %}
                <div class="col-md-3 col-sm-4">
                    <div class="single-new-arrival">
                        <div class="single-new-arrival-bg">
                            <img src="{{ y.arrivals_img.url }}" alt="new-arrivals images">
                            <div class="single-new-arrival-bg-overlay"></div>
                            <div class="new-arrival-cart">
                                <p>
                                    <span class="lnr lnr-cart"></span>
                                    <a href="#">{% trans "karta qoshish" %}</a>
                                </p>
                                <p class="arrival-review pull-right">
                                    <span class="lnr lnr-heart"></span>
                                    <span class="lnr lnr-frame-expand"></span>
                                </p>
                            </div>
                        </div>
                        <h4><a href="{% url 'furn:arrivals_detal' y.pk %}">{{ y.arrivals_title }}</a></h4>
                        <p class="arrival-product-price">${{ y.arrivals_price }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!--/.container-->

</section>